###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: api-gateway-service
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka


### 配置网关反向代理
zuul:
  routes:
    api-a:
      ### 以 /member-service/访问转发到会员服务
      path: /member-service/**
      serviceId: member-service
    api-b:
      ### 以 /verify-login-service/访问转发到登录验证服务接口
      path: /verify-login-service/**
      serviceId: verify-login-service
