version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper-data:/data
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost   #Docker宿主机IP（如果你要配置多个brokers，就不能设置为 localhost 或 127.0.0.1）
      KAFKA_MESSAGE_MAX_BYTES: 2000000   #kafka(message.max.bytes) 会接收单个消息size的最大限制，默认值为1000000 , ≈1M
      KAFKA_CREATE_TOPICS: "Topic1:3:3"   #初始创建的topics，可以不设置,Topic 1 will have 1 partition and 3 replicas, Topic 2 will have 1 partition, 1 replica and a cleanup.policy set to compact
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-data:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  kafka-manager:  #可视化kafka WEB管理平台
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181

volumes:
  zookeeper-data:
  kafka-data:
